# Generated by Django 5.1.6 on 2025-07-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_customer_organization_order_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='laundry.organization'),
            preserve_default=False,
        ),
    ]
