# Generated by Django 5.1.6 on 2025-07-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_branch_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry.organization'),
        ),
    ]
