# Generated by Django 5.1.6 on 2025-07-28 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_remove_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country_code',
            field=models.CharField(default='+91', help_text='Country Code (e.g., +91)', max_length=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(help_text='Enter 10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be exactly 10 digits')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
