# Generated by Django 5.1.6 on 2025-07-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_organization_country_code_organization_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
