# Generated by Django 5.1.6 on 2025-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0007_organization_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
