# Generated by Django 5.1.6 on 2025-07-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0008_alter_organization_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_branches',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='allowed_staff',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='validity_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='validity_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
