# Generated by Django 5.1.6 on 2025-07-29 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0010_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='validity_end',
            new_name='plan_end_date',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='validity_start',
            new_name='plan_start_date',
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundry.plan'),
        ),
    ]
