# Generated by Django 5.1.6 on 2025-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0012_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='e.g., BR001, BR002', max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'code')},
        ),
    ]
