# Generated by Django 5.1.6 on 2025-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0015_logoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
