# Generated by Django 5.1.6 on 2025-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0016_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
