# Generated by Django 5.1.6 on 2025-07-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0017_staff_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='allowed_branches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='allowed_staff',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
