# Generated by Django 5.1.6 on 2025-08-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0018_alter_organization_allowed_branches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dry_clean_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
