# Generated by Django 5.1.6 on 2025-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0019_article_dry_clean_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dryclean_items',
            field=models.TextField(blank=True, help_text='Jacket × 2\nSaree × 1'),
        ),
    ]
