# Generated by Django 5.1.6 on 2025-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0020_order_dryclean_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dryclean_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ironing_items',
        ),
        migrations.AddField(
            model_name='order',
            name='services_items',
            field=models.TextField(blank=True, help_text='Use format: Service: Item Description × Quantity\nExample:\nIroning: Shirt (With Wash) × 2'),
        ),
    ]
