# Generated by Django 5.1.6 on 2025-08-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0021_remove_order_dryclean_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Ironing', 'Ironing'), ('Dryclean', 'Dryclean'), ('Other', 'Other')], max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('with_wash', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laundry.order')),
            ],
        ),
    ]
