# Generated by Django 5.1.6 on 2025-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
    ]
